# Generated by Django 4.0.5 on 2022-06-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.CharField(max_length=60, verbose_name='Исполнитель')),
                ('song_name', models.CharField(max_length=60, verbose_name='Название песни')),
                ('song_image', models.ImageField(upload_to='', verbose_name='Изображение группы')),
            ],
        ),
        migrations.CreateModel(
            name='MusicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=60, verbose_name='Название плейлиста')),
                ('music', models.ManyToManyField(to='MusicApp.musics')),
            ],
        ),
    ]
